model:
  type: rnng
  composer:
    type: birnn
    num_layers: 1
  distribution:
    type: class_based_softmax
    cluster: data/pet/wsj/generative/brown_c140.cluster
  embedding:
    size: 128
    max_norm: null
    norm_type: 2.0
    scale_grad_by_freq: false
    sparse: false
  memory:
    type: 'rnn'
  representation:
    type: vanilla
    size: 128
  rnn:
    type: lstm
    hidden_size: 128
    num_layers: 2
    bias: true
    dropout: 0.2
    bidirectional: false
  stack:
    type: 'rnn'
  threads: 1
  reverse_tokens: true
