model:
  type: parallel_rnng
  composer:
    type: birnn
    dropout: 0.2
    num_layers: 1
  embedding:
    max_norm: null
    norm_type: 2.0
    scale_grad_by_freq: false
    sparse: false
  representation:
    type: vanilla
    dropout: 0.2
  rnn:
    type: lstm
    hidden_size: 128
    num_layers: 2
    bias: true
    dropout: 0.2
    bidirectional: false
    weight_drop: null
  size:
    action: 16
    pos: 12
    token: 32
    rnn: 128
  unk_token_prob: 0.5
  action_emb_drop: null
  nt_emb_drop: null
  nt_com_emb_drop: null
  token_emb_drop: null
  pos_emb_drop: null
  sample_stack_size: 150
