model:
  type: rnng
  composer:
    type: birnn
    dropout: 0.3
    num_layers: 1
  distribution:
    type: class_based_softmax
    cluster: null
  embedding:
    max_norm: null
    norm_type: 2.0
    scale_grad_by_freq: false
    sparse: false
  representation:
    type: vanilla
    dropout: 0.3
  rnn:
    type: lstm
    hidden_size: 256
    num_layers: 2
    bias: true
    dropout: 0.3
    bidirectional: false
  size:
    action: 16
    rnn: 256
  threads: 1
