model:
  type: rnn_parser
  embedding:
    max_norm: null
    norm_type: 2.0
    scale_grad_by_freq: false
    sparse: false
  rnn:
    type: lstm
    hidden_size: 256
    num_layers: 3
    bias: true
    dropout: 0.25
    bidirectional: false
    weight_drop: null
  size:
    rnn: 256
    pos: 16
    token: 128
  dropout_type: normal
  action_emb_drop: null
  pos_emb_drop: null
  token_emb_drop: null
