loader:
  type: penn
  data_dir: data/penn_english_treebank/wsj/
  train_sections:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
  val_sections:
    - 24
  test_sections:
    - 23
