defaults:
  - iterator: evaluate
  - loader: wsj.gen.oracle
  - data: val
  - sampler: ancestral
  - inferer: importance
load_dir: null
gpu: null
seed: null
name: rnng
hydra:
  run:
    dir: ./outputs/evaluate/${name}/${now:%Y-%m-%d_%H-%M-%S}
