defaults:
  - type: gen
  - model: ${defaults.0.type}.parallel_rnng
  - iterator: ordered
  - loader: wsj.${defaults.0.type}.oracle
gpu: null
name: tmp
hydra:
  run:
    dir: ./outputs/time_stats/${name}
