defaults:
  - model_type: generative
  - model: ${defaults.0.model_type}.rnng
  - iterator: unordered
  - loader: artificial.small.${defaults.0.model_type}.oracle
  - loss: negative_log_likelihood
  - optimizer: adam
  - stopping_criterion: epochs
hydra:
  run:
    dir: ./outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}
