defaults:
  - type: generative
  - model: ${defaults.0.type}.rnng
  - iterator: unordered
  - loader: artificial.small.${defaults.0.type}.oracle
  - loss: negative_log_likelihood
  - optimizer: adam
  - stopping_criterion: epochs
  - checkpoint: never
name: rnng
load_checkpoint: null
hydra:
  run:
    dir: ./outputs/train/${name}/${now:%Y-%m-%d_%H-%M-%S}
