defaults:
  - type: gen
  - model: ${defaults.0.type}.parallel_rnng
  - iterator: ordered
  - loader: wsj.${defaults.0.type}.oracle
  - loss: negative_log_likelihood
  - optimizer: adam
  - lr_scheduler: constant
  - stopping_criterion: manual
  - checkpoint: never
  - evaluator: batch
name: tmp
log_train_every: 1
load_checkpoint: null
max_grad_norm: null
gpu: null
seed: null
hydra:
  run:
    dir: ./outputs/train/${name}
