defaults:
  - type: gen
  - model: ${defaults.0.type}.rnng
  - iterator: unordered
  - loader: wsj.${defaults.0.type}.oracle
  - loss: negative_log_likelihood
  - optimizer: adam
  - stopping_criterion: early_stopping
  - checkpoint: never
  - evaluator: batch
name: rnng
load_checkpoint: null
gpu: null
seed: null
hydra:
  run:
    dir: ./outputs/train/${name}/${now:%Y-%m-%d_%H-%M-%S}
